sudo: required
services:
  - docker

before_install:
  - docker build -t kehindeadewusi/reacting -f Dockerfile.dev

script:
  - docker run -e CI=true kehindeadewusi/reacting npm run test -- --coverage
